### PR TITLE
Strip querystring from asset path so mix manifest key matches filename

### LINKED ISSUE #39: Additional information for server-side setup: must disable Cake asset timestamping
**Is your feature request related to a problem? Please describe.**
Yes, a problem I had while setting up this library on a Cake3 application. With asset timestamping (`Asset.timestamp => true or 'force'` in app.php) enabled, AssetMix will fail to find the manifest. This is because Cake appends a timestamp to the end of the asset URL which means the "path" is not found in the mix manifest.

I'm new to this plugin and to mix/manifests in general, so I apologize if my terminology is inaccurate.

**Describe the solution you'd like**
Either update the docs to indicate that this setting should be turned off OR find a way for the manifest loader to ignore the timestamp in the query string when loading the asset file.

**Describe alternatives you've considered**
N/A

**Additional context**
Screen Shot 2022-04-29 at 10 30 35

### PR DESCRIPTION
**Pull request by jrbakooba**
Resolves #39

### CODE REVIEW

**Comment by jrbakooba** [comment]
Whoops @ishanvyas22 I apologize, looks like my code formatters ran automatically. Let me know if you want me to revert those formatting changes.

**Comment by ishanvyas22** [comment]
> Whoops @ishanvyas22 I apologize, looks like my code formatters ran automatically. Let me know if you want me to revert those formatting changes.

Yup, pls revert it.

**Review by ishanvyas22 — CHANGES_REQUESTED** [review]
Can you please add test for this?

**Comment by jrbakooba** [comment]
Apologies for the delay. I have added two tests for checking stripping the query string.

I also reverted all the formatting changes.

**Comment by jrbakooba** [comment]
Oh, I see phpstan has something to say as well. I will fix that.

**Review by ishanvyas22 — APPROVED** [review]

**Comment by ishanvyas22** [comment]
Thanks @jrbakooba

**Pull request merged**
